<?php

namespace AboutBundle\Repository;

/**
 * VariousContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariousContentRepository extends \Doctrine\ORM\EntityRepository
{
}
