team_team:
    resource: "@TeamBundle/Resources/config/routing/team.yml"
    prefix:   /team

team_member:
    resource: "@TeamBundle/Resources/config/routing/member.yml"
    prefix:   /member

team_homepage:
    path:     /
    defaults: { _controller: TeamBundle:Default:index }
